---
title: "Splines en R"
output:
  pdf_document: default
  html_notebook: default
---

Carguemos los datos y la librería necesarias
```{r}
# install.packages("ISLR") #Instalar para cargar el dataset
library(ISLR)
attach(Wage)
library(splines)
```

Wage dataset
```{r}
head(Wage)
```

Creando conjunto de prueba
```{r}
agelims = range ( age )
age.grid = seq ( from = agelims [1] , to = agelims [2])
```


### Spline cúbico (B-spline)
```{r}
fit = lm ( wage~bs ( age , knots = c (25 ,40 ,60) ) , data = Wage )
pred = predict ( fit , newdata = list ( age = age.grid ) , se = T )
plot ( age , wage , col =" gray ") 
lines ( age.grid , pred$fit , lwd =2)
lines ( age.grid , pred$fit +2* pred$se , lty ="dashed") 
lines ( age.grid , pred$fit -2* pred$se , lty ="dashed")
```

### Spline Natural

```{r}
fit2 = lm ( wage~ns ( age , df =4) , data = Wage )

pred2 = predict ( fit2 , newdata = list ( age = age.grid ) , se = T ) 

# Grafica pasada
plot ( age , wage , col =" gray ") 
lines ( age.grid , pred$fit , lwd =2)
lines ( age.grid , pred$fit +2* pred$se , lty ="dashed") 
lines ( age.grid , pred$fit -2* pred$se , lty ="dashed")

# Grafica del spline natural
lines ( age.grid , pred2$fit , col = "red" , lwd =2)
```

## Spline suave  (Smooth Spline)

```{r}
fit = smooth.spline ( age , wage , df =16) 
fit2 = smooth.spline ( age , wage , cv = TRUE )
fit2$df
```

```{r}
plot( age , wage , xlim = agelims , cex =.5 , col =" darkgrey ")
title(" Smoothing Spline ")
lines( fit , col =" red " , lwd =2)
lines ( fit2 , col =" blue " , lwd =2) 
legend ("topright" , legend = c("16 DF" ,"6.8 DF") , col = c("red","blue") , lty =1 , lwd =2 , cex =.8)
```

